name       : paper-icon-theme
version    : 1.3.2
release    : 1
source     :
    - https://github.com/snwh/paper-icon-theme/archive/v1.3.2.tar.gz : 44bfefde469e3d968e4c530f7ec09dcacba82da5913ffc8a9ac44addad449ce3
license    : 
    - CC-SA-4.0
    - LGPL-3.0
component  : desktop.theme
summary    : Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
description: |
    Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
