name       : paper-icon-theme
version    : 1.3.3
release    : 2
source     :
    - https://github.com/snwh/paper-icon-theme/archive/v1.3.3.tar.gz : 191b2d67f7b54baa37a6f598150c4d85417ca8298f4600e0b9893050d38bca3a
license    :
    - CC-SA-4.0
    - LGPL-3.0
component  : desktop.theme
summary    : Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
description: |
    Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
