name       : paper-icon-theme
version    : 1.4.0
release    : 4
source     :
    - https://github.com/snwh/paper-icon-theme/archive/v1.4.0.tar.gz : b90f3a84634572bcba76cdd0c2a0d305a5c521c2054d3d390edffda5f233928b
license    :
    - CC-SA-4.0
    - LGPL-3.0
component  : desktop.theme
summary    : Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
description: |
    Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
