name       : paper-icon-theme
version    : 1.5.0
release    : 6
source     :
    - git|https://github.com/snwh/paper-icon-theme : aa3e8af7a1f0831a51fd7e638a4acb077a1e5188
license    :
    - CC-SA-4.0
    - LGPL-3.0-only
component  : desktop.theme
summary    : Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
description: |
    Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
