name       : paper-icon-theme
version    : 1.5.0
release    : 5
source     :
    - https://github.com/snwh/paper-icon-theme/archive/v.1.5.0.tar.gz : 62f21dfe95ece481e5c635480f32347f1ad27ea66b2ef0526fe799090b298ece
license    :
    - CC-SA-4.0
    - LGPL-3.0-only
component  : desktop.theme
summary    : Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
description: |
    Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
