name       : paper-icon-theme
version    : 1.3.4
release    : 3
source     :
    - https://github.com/snwh/paper-icon-theme/archive/v1.3.4.tar.gz : b32fc5f084b6be7dfe8275b5f1edfdcafe6200da7df90c13cc1d2628dd50c843
license    :
    - CC-SA-4.0
    - LGPL-3.0
component  : desktop.theme
summary    : Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
description: |
    Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
